apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-prediction
spec:
  replicas: 3
  selector:
    matchLabels:
      app: churn-app
  template:
    metadata:
      labels:
        app: churn-app
    spec:
      containers:
      - name: churn-container
        image: us-east1-docker.pkg.dev/mlops-cht1-model-deployment/ml-repo/churn-prediction:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: churn-service
spec:
  type: LoadBalancer
  selector:
    app: churn-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
